'use client';
import { useState, useMemo } from 'react';
import Link from 'next/link';
import { ArrowLeft, MapPin, CalendarDays, ChevronRight, Map, List, ArrowUpRight } from 'lucide-react';
import { trails } from '@/lib/data/mock';
import { usePlanner } from '@/lib/store';
import { formatDate } from '@/lib/utils';
import { TripMap } from '@/components/map/trip-map';
import { TripTimeline, LodgingCard, DaySummary } from './trip-timeline';
import { Button } from '@/components/ui/button';
import type { Trip } from '@/lib/types';
import { AuthGate } from '@/components/auth/auth-gate';
export function TripHeader({trip}:{trip:Trip}) {return <div className="planner-header"><div><Link href="/trips" className="back-link"><ArrowLeft size={14}/> My trips</Link><h1>{trip.name}</h1><div className="trip-meta"><span><MapPin size={14}/>{trip.destination}</span><span><CalendarDays size={14}/>{formatDate(trip.startDate)} – {formatDate(trip.endDate)}, {trip.startDate.slice(0,4)}</span></div></div><div className="planner-header-right"><span className="saved-indicator"><i/>Saved to your account</span><Button variant="outline" asChild><Link href="/explore">Discover trails <ArrowUpRight size={15}/></Link></Button></div></div>}
export function TripDaySelector({trip,selected,onSelect}:{trip:Trip;selected:number;onSelect:(index:number)=>void}) {return <div className="day-selector" aria-label="Trip days">{trip.days.map((day,i)=><button key={day.id} aria-pressed={selected===i} onClick={()=>onSelect(i)} className={selected===i?'selected':''}><span>Day {String(i+1).padStart(2,'0')}</span><small>{formatDate(day.date)}</small>{day.stops.length>0&&<i/>}</button>)}</div>}
export function Planner({id}:{id:string}) {return <AuthGate><UserPlanner id={id}/></AuthGate>}
function UserPlanner({id}:{id:string}) {const stored=usePlanner(s=>s.trips);const loading=usePlanner(s=>s.loading);const error=usePlanner(s=>s.error);const load=usePlanner(s=>s.load);const trip=stored.find(t=>t.id===id);const [index,setIndex]=useState(0);const [showMap,setShowMap]=useState(false);const day=trip?.days[index]??trip?.days[0];const selectedTrails=useMemo(()=>day?.stops.flatMap(s=>{const t=trails.find(t=>t.id===s.trailId);return t?[t]:[]})??[],[day]);if(loading)return <main className="section page-main"><p role="status">Loading your trip…</p></main>;if(error)return <main className="section page-main"><p role="alert">{error}</p><Button onClick={()=>void load()}>Try again</Button></main>;if(!trip||!day)return <main className="section page-main"><div className="empty-state"><h1>This trip isn’t available.</h1><p>Choose a trip from your account or create a new adventure.</p><Button asChild><Link href="/trips">Back to my trips</Link></Button></div></main>;return <main className="planner-page"><TripHeader trip={trip}/><div className="planner-toolbar"><div className="planner-breadcrumb">Itinerary <ChevronRight size={13}/><span>{trip.days.length} days of possibility</span></div><span className="mock-label">SAMPLE DATA · TIMING PREVIEW</span><button className="mobile-map-toggle" onClick={()=>setShowMap(!showMap)}>{showMap?<List size={16}/>:<Map size={16}/>} {showMap?'Itinerary':'Map'}</button></div><div className={`planner-layout ${showMap?'show-map':''}`}><aside className="planner-sidebar"><TripDaySelector trip={trip} selected={index} onSelect={setIndex}/><div className="planner-scroll"><div className="day-heading"><p className="eyebrow">{new Date(day.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><h2>{day.title}</h2><p>{day.stops.length?`${day.stops.length} stops · A good day to be outside`:'An open day, ready for adventure.'}</p></div><LodgingCard trip={trip}/><TripTimeline key={day.id} trip={trip} day={day}/><DaySummary day={day}/></div></aside><section aria-label="Trip map" className="planner-map"><TripMap trails={selectedTrails}/><div className="map-trip-card"><span className="map-card-icon"><MapPin size={21}/></span><div><strong>{trip.destination}</strong><p>Day {index+1} <span>·</span> {day.stops.length} stops on your itinerary</p></div></div></section></div></main>}
