'use client';
import Link from 'next/link';
import { Car, MapPin, ArrowUpRight, Trash2, Plus, BedDouble, Route, Mountain, Sun, Sunset, Clock, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { trails } from '@/lib/data/mock';
import { usePlanner } from '@/lib/store';
import { TrailStats } from '@/components/trails/trail-card';
import { Button } from '@/components/ui/button';
import type { Trip, TripDay, TripStop as Stop } from '@/lib/types';
export function LodgingCard({trip}:{trip:Trip}) {return <div className="lodging-card"><span className="lodging-icon"><BedDouble size={20}/></span><div><span className="eyebrow">YOUR BASECAMP</span><h3>{trip.lodging.name}</h3><p>{trip.lodging.type} · {trip.destination}</p></div></div>}
export function DriveSegment({minutes}:{minutes:number}) {return <div className="drive-segment"><Car size={14}/><span>{minutes ? `${minutes} min drive` : 'Drive time not calculated'}</span><span className="drive-line"/></div>}
export function TripStop({stop,index,tripId,dayId}:{stop:Stop;index:number;tripId:string;dayId:string}) {const trail=trails.find(t=>t.id===stop.trailId);const remove=usePlanner(s=>s.removeStop);if(!trail)return null;return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:0.25,delay:index*0.05}} className="timeline-stop"><span className="timeline-number">{index+1}</span><div className="stop-time">{stop.start}</div><article className="stop-card"><Link href={`/trails/${trail.slug}`} className="stop-photo"><img src={trail.photo} alt={trail.name}/></Link><div className="stop-body"><div className="flex items-center justify-between gap-2"><span className={`difficulty inline-difficulty ${trail.difficulty.toLowerCase()}`}>{trail.difficulty} hike</span><button className="remove-stop" title="Remove stop" aria-label={`Remove ${trail.name}`} onClick={()=>remove(tripId,dayId,stop.id)}><Trash2 size={14}/></button></div><Link className="stop-title" href={`/trails/${trail.slug}`}>{trail.name}<ArrowUpRight size={16}/></Link><TrailStats trail={trail}/><div className="stop-finish"><Clock size={12}/> Estimated finish <strong>{stop.finish}</strong></div></div></article></motion.div>}
export function TripTimeline({trip,day}:{trip:Trip;day:TripDay}) {return <div className="trip-timeline"><div className="timeline-start"><span className="timeline-home"><MapPin size={15}/></span><span className="stop-time">{day.stops.length?'7:00 AM':'YOUR STARTING POINT'}</span><h3>Leave {trip.lodging.name}</h3><p>A fresh start. A day of possibilities.</p></div>{day.stops.map((stop,i)=><div key={stop.id}><DriveSegment minutes={stop.driveMinutes}/><TripStop stop={stop} index={i} tripId={trip.id} dayId={day.id}/></div>)}<Button asChild variant="outline" className="add-stop"><Link href="/explore"><Plus size={17}/>{day.stops.length?'Add another stop':'Find your first trail'}</Link></Button></div>}
export function DaySummary({day}:{day:TripDay}) {const selected=day.stops.map(s=>trails.find(t=>t.id===s.trailId)).filter(t=>!!t);const miles=selected.reduce((sum,t)=>sum+t.distance,0);const elevation=selected.reduce((sum,t)=>sum+t.elevation,0);const minutes=day.stops.reduce((sum,s)=>sum+s.driveMinutes,0);const isSample=day.id==='oregon-1'&&day.stops.length===3&&day.stops.every((s,i)=>s.id===`stop-${i+1}`);return <section className="day-summary"><div className="flex items-center justify-between"><h3>Your day at a glance</h3><span>DAY SUMMARY</span></div><div className="summary-grid"><div><Route size={17}/><strong>{miles.toFixed(1)} <small>mi</small></strong><span>Hiking distance</span></div><div><Mountain size={17}/><strong>{elevation.toLocaleString()} <small>ft</small></strong><span>Elevation gain</span></div><div><Car size={17}/><strong>{isSample?`${minutes}`:'—'} <small>{isSample?'min':''}</small></strong><span>Driving time</span></div></div><div className="sun-times"><span><Sun size={15}/>Sunrise <strong>{isSample?'7:25 AM':'—'}</strong></span><span><Sunset size={15}/>Sunset <strong>{isSample?'6:18 PM':'—'}</strong></span></div>{isSample?<div className="daylight-status"><CheckCircle2 size={17}/><div>Plenty of daylight to wander.<small>Estimated finish 1:01 PM · 5 hr 17 min before sunset</small></div></div>:<div className="daylight-status"><Clock size={17}/><div>Your day is taking shape.<small>Driving and daylight calculations are coming later.</small></div></div>}<p className="summary-note">{isSample?'Timing and daylight are illustrative sample data.':'Distances and elevation are summed from sample trail data.'}</p></section>}
